package com.example.dealnest.ui.screens

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Check
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.outlined.Lightbulb
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Dialog
import com.example.dealnest.model.Project
import com.example.dealnest.ui.DealNestViewModel
import com.example.dealnest.ui.components.StatusChip
import com.example.dealnest.util.AiProposalAssistant
import com.example.ui.theme.DealCyanPrimary
import com.example.ui.theme.DealEmerald
import com.example.ui.theme.DealIndigo

@Composable
fun SendProposalDialog(
    viewModel: DealNestViewModel,
    project: Project,
    onDismiss: () -> Unit
) {
    val currentUser by viewModel.currentUser.collectAsState()
    val selectedCurrency by viewModel.selectedCurrency.collectAsState()

    var proposedPriceText by remember { mutableStateOf(project.budgetMin.toInt().toString()) }
    var deliveryDaysText by remember { mutableStateOf(project.deadlineDays.toString()) }
    var coverMessage by remember {
        mutableStateOf(
            "Hi ${project.clientName}! I have extensive experience building ${project.websiteType} websites with ${project.requiredSkills}. I'd love to deliver this with clean code and high performance."
        )
    }
    var portfolioLink by remember {
        mutableStateOf(
            currentUser.portfolioLinks.split(",").firstOrNull()?.trim() ?: "https://dealnest.com/p/${currentUser.name.lowercase().replace(" ", "-")}"
        )
    }
    var isAiGenerated by remember { mutableStateOf(false) }
    var selectedTone by remember { mutableStateOf("Professional") }
    val tones = listOf("Professional", "Technical", "Persuasive")
    val context = androidx.compose.ui.platform.LocalContext.current
    var errorText by remember { mutableStateOf<String?>(null) }

    fun generateWithTone(tone: String) {
        val generated = AiProposalAssistant.generateProposal(project, currentUser, tone)
        proposedPriceText = generated.suggestedPrice.toInt().toString()
        deliveryDaysText = generated.suggestedDeliveryDays.toString()
        coverMessage = generated.fullPitchMessage
        selectedTone = tone
        isAiGenerated = true
    }

    Dialog(onDismissRequest = onDismiss) {
        Card(
            shape = RoundedCornerShape(20.dp),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
            modifier = Modifier
                .fillMaxWidth()
                .fillMaxHeight(0.90f)
                .testTag("send_proposal_dialog")
        ) {
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(20.dp)
            ) {
                // Header
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Column(modifier = Modifier.weight(1f)) {
                        Text(
                            text = "Submit Deal Proposal",
                            fontSize = 18.sp,
                            fontWeight = FontWeight.Bold,
                            color = MaterialTheme.colorScheme.onSurface
                        )
                        Text(
                            text = project.title,
                            fontSize = 12.sp,
                            color = DealCyanPrimary,
                            maxLines = 1
                        )
                    }

                    IconButton(onClick = onDismiss) {
                        Icon(Icons.Default.Close, contentDescription = "Close")
                    }
                }

                Spacer(modifier = Modifier.height(8.dp))

                // Project Context Strip
                Surface(
                    shape = RoundedCornerShape(12.dp),
                    color = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Row(
                        modifier = Modifier.padding(10.dp),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text(
                            text = "Client Budget: ${viewModel.formatPrice(project.budgetMin)} - ${viewModel.formatPrice(project.budgetMax)}",
                            fontSize = 11.sp,
                            fontWeight = FontWeight.Bold,
                            color = DealEmerald
                        )
                        StatusChip(statusText = project.websiteType)
                    }
                }

                Spacer(modifier = Modifier.height(10.dp))

                // AI Proposal Assistant Action Button (Feature 7)
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    OutlinedButton(
                        onClick = { generateWithTone(selectedTone) },
                        shape = RoundedCornerShape(12.dp),
                        border = BorderStroke(1.5.dp, DealCyanPrimary),
                        colors = ButtonDefaults.outlinedButtonColors(
                            containerColor = DealCyanPrimary.copy(alpha = 0.08f)
                        ),
                        modifier = Modifier
                            .weight(1f)
                            .testTag("generate_ai_proposal_button")
                    ) {
                        Icon(
                            Icons.Default.AutoAwesome,
                            contentDescription = null,
                            tint = DealCyanPrimary,
                            modifier = Modifier.size(16.dp)
                        )
                        Spacer(modifier = Modifier.width(6.dp))
                        Text(
                            text = if (isAiGenerated) "Regenerate AI Proposal" else "Generate Proposal with AI",
                            fontSize = 12.sp,
                            fontWeight = FontWeight.Bold,
                            color = DealCyanPrimary
                        )
                    }

                    if (isAiGenerated) {
                        IconButton(
                            onClick = {
                                val clipboard = context.getSystemService(android.content.Context.CLIPBOARD_SERVICE) as android.content.ClipboardManager
                                val clip = android.content.ClipData.newPlainText("AI Proposal", coverMessage)
                                clipboard.setPrimaryClip(clip)
                                viewModel.emitSnackbar("Proposal copied to clipboard!")
                            },
                            modifier = Modifier.testTag("copy_proposal_button")
                        ) {
                            Icon(Icons.Filled.ContentCopy, contentDescription = "Copy Proposal", tint = DealCyanPrimary)
                        }
                    }
                }

                // AI Tone Rewriter & Status
                if (isAiGenerated) {
                    Spacer(modifier = Modifier.height(6.dp))
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(6.dp)
                    ) {
                        Text("Rewrite Tone:", fontSize = 10.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)
                        tones.forEach { tone ->
                            FilterChip(
                                selected = selectedTone == tone,
                                onClick = { generateWithTone(tone) },
                                label = { Text(tone, fontSize = 10.sp) },
                                modifier = Modifier.height(30.dp)
                            )
                        }
                    }

                    Surface(
                        shape = RoundedCornerShape(8.dp),
                        color = DealEmerald.copy(alpha = 0.12f),
                        border = BorderStroke(1.dp, DealEmerald.copy(alpha = 0.3f)),
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(top = 6.dp)
                    ) {
                        Row(
                            modifier = Modifier.padding(8.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(6.dp)
                        ) {
                            Icon(Icons.Default.Check, contentDescription = null, tint = DealEmerald, modifier = Modifier.size(14.dp))
                            Text(
                                text = "Generated 8 structured sections (Opening, Understanding, Solution, Approach, Timeline, Pricing, Questions, Closing). Review and edit before sending.",
                                fontSize = 10.sp,
                                color = DealEmerald,
                                lineHeight = 13.sp
                            )
                        }
                    }
                }

                Spacer(modifier = Modifier.height(10.dp))

                // Form Scrollable
                Column(
                    modifier = Modifier
                        .weight(1f)
                        .verticalScroll(rememberScrollState()),
                    verticalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                        OutlinedTextField(
                            value = proposedPriceText,
                            onValueChange = { proposedPriceText = it },
                            label = { Text("Your Price (${selectedCurrency.code})") },
                            modifier = Modifier.weight(1f).testTag("proposal_price_input")
                        )
                        OutlinedTextField(
                            value = deliveryDaysText,
                            onValueChange = { deliveryDaysText = it },
                            label = { Text("Est. Days") },
                            modifier = Modifier.weight(1f).testTag("proposal_days_input")
                        )
                    }

                    OutlinedTextField(
                        value = coverMessage,
                        onValueChange = { coverMessage = it },
                        label = { Text("Pitch & Approach to Client (Fully Editable)") },
                        placeholder = { Text("Describe your project approach, milestones, and tech stack...") },
                        minLines = 6,
                        modifier = Modifier.fillMaxWidth().testTag("proposal_message_input")
                    )

                    OutlinedTextField(
                        value = portfolioLink,
                        onValueChange = { portfolioLink = it },
                        label = { Text("Live Portfolio / Case Study Link") },
                        placeholder = { Text("https://dealnest.com/p/your-name") },
                        modifier = Modifier.fillMaxWidth()
                    )

                    if (errorText != null) {
                        Text(errorText ?: "", color = MaterialTheme.colorScheme.error, fontSize = 12.sp)
                    }

                    Text(
                        text = "🔒 Manual Review: The AI never automatically sends proposals. You must review and confirm before submission.",
                        fontSize = 10.sp,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }

                Spacer(modifier = Modifier.height(10.dp))

                Button(
                    onClick = {
                        val price = proposedPriceText.toDoubleOrNull()
                        val days = deliveryDaysText.toIntOrNull()
                        if (price == null || days == null || coverMessage.isBlank()) {
                            errorText = "Please fill in price, days, and a message."
                            return@Button
                        }

                        viewModel.sendProposal(
                            project = project,
                            proposedPrice = price,
                            deliveryDays = days,
                            coverMessage = coverMessage,
                            portfolioLink = portfolioLink
                        )
                    },
                    shape = RoundedCornerShape(12.dp),
                    colors = ButtonDefaults.buttonColors(
                        containerColor = DealCyanPrimary,
                        contentColor = Color.Black
                    ),
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(46.dp)
                        .testTag("submit_proposal_button")
                ) {
                    Text("Send Proposal to Client", fontWeight = FontWeight.Bold)
                }
            }
        }
    }
}
